# Generated by Django 3.2.14 on 2022-07-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(choices=[('JANUARY', 'JAN'), ('FEBRUARY', 'FEB'), ('MARCH', 'MAR'), ('APRIL', 'APR')], default='JANUARY', max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='publication_date')),
            ],
        ),
        migrations.CreateModel(
            name='t_c_Db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('registration_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
