# Generated by Django 3.2.15 on 2022-08-10 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_auto_20220810_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privacypolicyquestions',
            name='acceptPayments',
        ),
        migrations.RemoveField(
            model_name='privacypolicyquestions',
            name='collectPersonalInfo',
        ),
        migrations.RemoveField(
            model_name='privacypolicyquestions',
            name='containAds',
        ),
        migrations.RemoveField(
            model_name='privacypolicyquestions',
            name='discloseCollectInfo',
        ),
        migrations.RemoveField(
            model_name='privacypolicyquestions',
            name='disclosePerInfo',
        ),
        migrations.RemoveField(
            model_name='privacypolicyquestions',
            name='marketingCommnuication',
        ),
        migrations.RemoveField(
            model_name='privacypolicyquestions',
            name='other_personalInfo',
        ),
        migrations.RemoveField(
            model_name='privacypolicyquestions',
            name='secureMeausre',
        ),
        migrations.RemoveField(
            model_name='privacypolicyquestions',
            name='upPostContent',
        ),
        migrations.AlterField(
            model_name='privacypolicyquestions',
            name='cityTown',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='privacypolicyquestions',
            name='compAddressLine',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='privacypolicyquestions',
            name='other_policyUseChoice',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='privacypolicyquestions',
            name='userCreateAccount',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='privacypolicyquestions',
            name='versionDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='privacypolicyquestions',
            name='websiteOffer',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='privacypolicyquestions',
            name='zipCode',
            field=models.IntegerField(null=True),
        ),
    ]
