# Generated by Django 4.0.6 on 2022-08-03 09:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='company',
            field=models.CharField(default='Empty Field', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='contactNumber',
            field=models.IntegerField(default='23400000000'),
            preserve_default=False,
        ),
    ]
