# Generated by Django 4.0.6 on 2022-08-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_usermodel_address_usermodel_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='address',
            new_name='userAddress',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='contactNumber',
            field=models.IntegerField(default=23480000000),
        ),
    ]
