# Generated by Django 3.2.12 on 2022-08-13 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_auto_20220812_1154'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
        migrations.RemoveField(
            model_name='privacypolicyquestions',
            name='cityTown',
        ),
        migrations.RemoveField(
            model_name='privacypolicyquestions',
            name='compAddressLine',
        ),
        migrations.RemoveField(
            model_name='privacypolicyquestions',
            name='companyEmail',
        ),
        migrations.RemoveField(
            model_name='privacypolicyquestions',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='privacypolicyquestions',
            name='legalName',
        ),
        migrations.RemoveField(
            model_name='privacypolicyquestions',
            name='phoneNumber',
        ),
        migrations.RemoveField(
            model_name='privacypolicyquestions',
            name='provideEmailAdd',
        ),
        migrations.RemoveField(
            model_name='privacypolicyquestions',
            name='provideService',
        ),
        migrations.RemoveField(
            model_name='privacypolicyquestions',
            name='tradeNameBusiness',
        ),
        migrations.RemoveField(
            model_name='privacypolicyquestions',
            name='userCreateAccount',
        ),
        migrations.RemoveField(
            model_name='privacypolicyquestions',
            name='versionDate',
        ),
        migrations.RemoveField(
            model_name='privacypolicyquestions',
            name='websiteOffer',
        ),
        migrations.RemoveField(
            model_name='privacypolicyquestions',
            name='zipCode',
        ),
    ]
