# Generated by Django 3.2.12 on 2022-08-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_auto_20220810_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacypolicyquestions',
            name='real_estate',
            field=models.BooleanField(null=True),
        ),
    ]
