# Generated by Django 4.1 on 2022-08-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terms_and_condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('tnc_or_policy', models.CharField(max_length=50)),
                ('body', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='t_c_Db',
        ),
    ]
