# Generated by Django 3.2.15 on 2022-08-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_auto_20220806_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicyQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_policyUseChoice', models.CharField(max_length=50)),
                ('userLocate', models.BooleanField()),
                ('userCreateAccount', models.BooleanField()),
                ('websiteOffer', models.BooleanField()),
                ('other_personalInfo', models.CharField(max_length=50)),
                ('collectPersonalInfo', models.BooleanField()),
                ('marketingCommnuication', models.BooleanField()),
                ('acceptPayments', models.BooleanField()),
                ('containAds', models.BooleanField()),
                ('upPostContent', models.BooleanField()),
                ('disclosePerInfo', models.BooleanField()),
                ('discloseCollectInfo', models.BooleanField()),
                ('secureMeausre', models.BooleanField()),
                ('provideService', models.BooleanField()),
                ('provideEmailAdd', models.CharField(max_length=50)),
                ('legalName', models.CharField(max_length=200)),
                ('tradeNameBusiness', models.BooleanField()),
                ('companyEmail', models.CharField(max_length=50)),
                ('phoneNumber', models.IntegerField()),
                ('fax', models.IntegerField()),
                ('compAddressLine', models.CharField(max_length=200)),
                ('cityTown', models.CharField(max_length=150)),
                ('zipCode', models.IntegerField()),
                ('versionDate', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(default='JANUARY', max_length=200),
        ),
    ]
