# Generated by Django 3.2.15 on 2022-08-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0006_auto_20220807_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypolicyquestions',
            name='acceptPayments',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='privacypolicyquestions',
            name='cityTown',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='privacypolicyquestions',
            name='collectPersonalInfo',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='privacypolicyquestions',
            name='compAddressLine',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='privacypolicyquestions',
            name='companyEmail',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='privacypolicyquestions',
            name='containAds',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='privacypolicyquestions',
            name='discloseCollectInfo',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='privacypolicyquestions',
            name='disclosePerInfo',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='privacypolicyquestions',
            name='fax',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='privacypolicyquestions',
            name='legalName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='privacypolicyquestions',
            name='marketingCommnuication',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='privacypolicyquestions',
            name='other_personalInfo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='privacypolicyquestions',
            name='other_policyUseChoice',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='privacypolicyquestions',
            name='phoneNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='privacypolicyquestions',
            name='provideEmailAdd',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='privacypolicyquestions',
            name='provideService',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='privacypolicyquestions',
            name='secureMeausre',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='privacypolicyquestions',
            name='tradeNameBusiness',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='privacypolicyquestions',
            name='upPostContent',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='privacypolicyquestions',
            name='userCreateAccount',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='privacypolicyquestions',
            name='userLocate',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='privacypolicyquestions',
            name='versionDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='privacypolicyquestions',
            name='websiteOffer',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='privacypolicyquestions',
            name='zipCode',
            field=models.IntegerField(null=True),
        ),
    ]
