# Generated by Django 3.2.12 on 2022-08-09 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_question'),
        ('userauth', '0007_auto_20220809_1422'),
    ]

    operations = [
    ]
