# Generated by Django 3.2.12 on 2022-08-09 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0006_terms_and_condition_delete_t_c_db'),
        ('userauth', '0009_auto_20220810_0015'),
    ]

    operations = [
    ]
